export const regionColors = {
    'East Blue': '#3498db',
    'West Blue': '#9b59b6',
    'North Blue': '#2ecc71',
    'South Blue': '#e67e22',
    'Grand Line': '#c8a951',
    'New World': '#000000',
    'Calm Belt': '#ffffff',
    'Red Line': '#e74c3c',
};

export const arcOrder = [
    'Romance Dawn',
    'N/a - Vivre Card',
    'One Piece Novel ZORO',
    'Orange Town',
    'Syrup Village',
    'Baratie',
    'Arlong Park',
    'Loguetown',
    'Reverse Mountain',
    'Whisky Peak',
    'Little Garden',
    'Drum Island',
    'Alabasta',
    "One Piece Ace's Story",
    'Jaya',
    'Skypiea',
    'Long Ring Long Land',
    'Water Seven',
    'Enies Lobby',
    'Post-Enies Lobby',
    'Thriller Bark',
    'Sabaody Archipelago',
    'Amazon Lily',
    'Impel Down',
    'Marineford',
    'Post-War',
    'Fish Man Island',
    'Punk Hazard',
    'Dressrosa',
    'Zou',
    'Whole Cake Island',
    'Levely',
    'Wano',
    'Egghead',
    'Elbaf',
];

export const arcDisplayNames = {
    'N/a - Vivre Card': 'Romance Dawn Arc',
    'One Piece Novel ZORO': 'Romance Dawn Arc',
    "One Piece Ace's Story": 'Alabasta Arc',
    'Romance Dawn': 'Romance Dawn Arc',
    'Orange Town': 'Orange Town Arc',
    'Syrup Village': 'Syrup Village Arc',
    'Baratie': 'Baratie Arc',
    'Arlong Park': 'Arlong Park Arc',
    'Loguetown': 'Loguetown Arc',
    'Reverse Mountain': 'Reverse Mountain Arc',
    'Whisky Peak': 'Whisky Peak Arc',
    'Little Garden': 'Little Garden Arc',
    'Drum Island': 'Drum Island Arc',
    'Alabasta': 'Alabasta Arc',
    'Jaya': 'Jaya Arc',
    'Skypiea': 'Skypiea Arc',
    'Long Ring Long Land': 'Long Ring Long Land Arc',
    'Water Seven': 'Water Seven Arc',
    'Enies Lobby': 'Enies Lobby Arc',
    'Post-Enies Lobby': 'Post-Enies Lobby Arc',
    'Thriller Bark': 'Thriller Bark Arc',
    'Sabaody Archipelago': 'Sabaody Archipelago Arc',
    'Amazon Lily': 'Amazon Lily Arc',
    'Impel Down': 'Impel Down Arc',
    'Marineford': 'Marineford Arc',
    'Post-War': 'Post-War Arc',
    'Fish Man Island': 'Fish-Man Island Arc',
    'Punk Hazard': 'Punk Hazard Arc',
    'Dressrosa': 'Dressrosa Arc',
    'Zou': 'Zou Arc',
    'Whole Cake Island': 'Whole Cake Island Arc',
    'Levely': 'Levely Arc',
    'Wano': 'Wano Arc',
    'Egghead': 'Egghead Arc',
    'Elbaf': 'Elbaf Arc',
};
